[build]
  command = "npm ci && CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://addiction-recovery-toolbox.onrender.com/api"
  NODE_VERSION = "18.20.5"
