[build]
  command = "export NODE_OPTIONS=--openssl-legacy-provider && npm ci && GENERATE_SOURCEMAP=false CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

[context.production.environment]
  # Using the correct Render.com service URL
  REACT_APP_API_URL = "https://addiction-recovery-toolbox.onrender.com/api"
  NODE_VERSION = "18.19.1"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyCLMGE_sn0QS6o7SpHySrb6ZNQJMoPoQSg"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "addiction-recovery-toolbox.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "addiction-recovery-toolbox"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "addiction-recovery-toolbox.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "912631685400"
  REACT_APP_FIREBASE_APP_ID = "1:912631685400:web:1383b1111eaecb45f63e6d"
