[build]
  command = "GENERATE_SOURCEMAP=false CI=false NODE_ENV=production npm ci && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

[context.production.environment]
  NODE_VERSION = "18.19.1"
  REACT_APP_API_URL = "https://addiction-recovery-toolbox.onrender.com/api"
